/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { TaxReturnWhereInput } from "./TaxReturnWhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class TaxReturnListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => TaxReturnWhereInput,
  })
  @ValidateNested()
  @Type(() => TaxReturnWhereInput)
  @IsOptional()
  @Field(() => TaxReturnWhereInput, {
    nullable: true,
  })
  every?: TaxReturnWhereInput;

  @ApiProperty({
    required: false,
    type: () => TaxReturnWhereInput,
  })
  @ValidateNested()
  @Type(() => TaxReturnWhereInput)
  @IsOptional()
  @Field(() => TaxReturnWhereInput, {
    nullable: true,
  })
  some?: TaxReturnWhereInput;

  @ApiProperty({
    required: false,
    type: () => TaxReturnWhereInput,
  })
  @ValidateNested()
  @Type(() => TaxReturnWhereInput)
  @IsOptional()
  @Field(() => TaxReturnWhereInput, {
    nullable: true,
  })
  none?: TaxReturnWhereInput;
}
export { TaxReturnListRelationFilter as TaxReturnListRelationFilter };
