/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TaxReturn } from "./TaxReturn";
import { TaxReturnCountArgs } from "./TaxReturnCountArgs";
import { TaxReturnFindManyArgs } from "./TaxReturnFindManyArgs";
import { TaxReturnFindUniqueArgs } from "./TaxReturnFindUniqueArgs";
import { DeleteTaxReturnArgs } from "./DeleteTaxReturnArgs";
import { TaxReturnService } from "../taxReturn.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => TaxReturn)
export class TaxReturnResolverBase {
  constructor(
    protected readonly service: TaxReturnService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TaxReturn",
    action: "read",
    possession: "any",
  })
  async _taxReturnsMeta(
    @graphql.Args() args: TaxReturnCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [TaxReturn])
  @nestAccessControl.UseRoles({
    resource: "TaxReturn",
    action: "read",
    possession: "any",
  })
  async taxReturns(
    @graphql.Args() args: TaxReturnFindManyArgs
  ): Promise<TaxReturn[]> {
    return this.service.taxReturns(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => TaxReturn, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TaxReturn",
    action: "read",
    possession: "own",
  })
  async taxReturn(
    @graphql.Args() args: TaxReturnFindUniqueArgs
  ): Promise<TaxReturn | null> {
    const result = await this.service.taxReturn(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TaxReturn)
  @nestAccessControl.UseRoles({
    resource: "TaxReturn",
    action: "delete",
    possession: "any",
  })
  async deleteTaxReturn(
    @graphql.Args() args: DeleteTaxReturnArgs
  ): Promise<TaxReturn | null> {
    try {
      return await this.service.deleteTaxReturn(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
