/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BankTransaction } from "./BankTransaction";
import { BankTransactionCountArgs } from "./BankTransactionCountArgs";
import { BankTransactionFindManyArgs } from "./BankTransactionFindManyArgs";
import { BankTransactionFindUniqueArgs } from "./BankTransactionFindUniqueArgs";
import { DeleteBankTransactionArgs } from "./DeleteBankTransactionArgs";
import { BankTransactionService } from "../bankTransaction.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => BankTransaction)
export class BankTransactionResolverBase {
  constructor(
    protected readonly service: BankTransactionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "BankTransaction",
    action: "read",
    possession: "any",
  })
  async _bankTransactionsMeta(
    @graphql.Args() args: BankTransactionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [BankTransaction])
  @nestAccessControl.UseRoles({
    resource: "BankTransaction",
    action: "read",
    possession: "any",
  })
  async bankTransactions(
    @graphql.Args() args: BankTransactionFindManyArgs
  ): Promise<BankTransaction[]> {
    return this.service.bankTransactions(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => BankTransaction, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "BankTransaction",
    action: "read",
    possession: "own",
  })
  async bankTransaction(
    @graphql.Args() args: BankTransactionFindUniqueArgs
  ): Promise<BankTransaction | null> {
    const result = await this.service.bankTransaction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => BankTransaction)
  @nestAccessControl.UseRoles({
    resource: "BankTransaction",
    action: "delete",
    possession: "any",
  })
  async deleteBankTransaction(
    @graphql.Args() args: DeleteBankTransactionArgs
  ): Promise<BankTransaction | null> {
    try {
      return await this.service.deleteBankTransaction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
