/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DoctorPrescriptionService } from "../doctorPrescription.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DoctorPrescriptionCreateInput } from "./DoctorPrescriptionCreateInput";
import { DoctorPrescription } from "./DoctorPrescription";
import { DoctorPrescriptionFindManyArgs } from "./DoctorPrescriptionFindManyArgs";
import { DoctorPrescriptionWhereUniqueInput } from "./DoctorPrescriptionWhereUniqueInput";
import { DoctorPrescriptionUpdateInput } from "./DoctorPrescriptionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DoctorPrescriptionControllerBase {
  constructor(
    protected readonly service: DoctorPrescriptionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DoctorPrescription })
  @nestAccessControl.UseRoles({
    resource: "DoctorPrescription",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDoctorPrescription(
    @common.Body() data: DoctorPrescriptionCreateInput
  ): Promise<DoctorPrescription> {
    return await this.service.createDoctorPrescription({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DoctorPrescription] })
  @ApiNestedQuery(DoctorPrescriptionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DoctorPrescription",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async doctorPrescriptions(
    @common.Req() request: Request
  ): Promise<DoctorPrescription[]> {
    const args = plainToClass(DoctorPrescriptionFindManyArgs, request.query);
    return this.service.doctorPrescriptions({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DoctorPrescription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DoctorPrescription",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async doctorPrescription(
    @common.Param() params: DoctorPrescriptionWhereUniqueInput
  ): Promise<DoctorPrescription | null> {
    const result = await this.service.doctorPrescription({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DoctorPrescription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DoctorPrescription",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDoctorPrescription(
    @common.Param() params: DoctorPrescriptionWhereUniqueInput,
    @common.Body() data: DoctorPrescriptionUpdateInput
  ): Promise<DoctorPrescription | null> {
    try {
      return await this.service.updateDoctorPrescription({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DoctorPrescription })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DoctorPrescription",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDoctorPrescription(
    @common.Param() params: DoctorPrescriptionWhereUniqueInput
  ): Promise<DoctorPrescription | null> {
    try {
      return await this.service.deleteDoctorPrescription({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
